# Date, Time and Timezone

## Library Import

All below are built-in libraries. There is a popular library named **pytz** not covered in this chapter as it is being deprecated. The replacement of pytz is **ZoneInfo**.

```{python, results='hold'}
from datetime import date, datetime, timedelta, time
from zoneinfo import ZoneInfo
```


## ZoneInfo {#zoneinfo}

**ZoneInfo** is the recommended built-in library to deal with timezone for **datetime** object. 

### Constructor

Initialize with zone name as key: **```ZoneInfo(key='<zone_name'>)```**.

```{python, results='hold'}
MY = ZoneInfo('Asia/Kuala_Lumpur')
NY = ZoneInfo('America/New_York')
UTC= ZoneInfo('UTC')

MY
NY
UTC
```

### Instance Attributes

```{python, results='hold'}
MY.key
```

## Date and Datetime

This is a built-in library by Python. There is no need to install this library.

**`date`** and **`datetime`** are both standard built-in python library.

**`datetime`** library contain four object classes:

- **date**: (year,month,day)
- **time**: (hour,minute,second)
- **datetime**: (year,month,day,hour,minute,second)
- **timedelta**: duration between two datetime or date object

### ISO8601

Refer [ISO8601 in Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) to understand the common ISO on date/datetime formatting.

```
UTC:    "2007-04-05T14:30Z"      #notice Z
GMT+8:  "2007-04-05T12:30+08:00  #notice +08:00
GMT+8:  "2007-04-05T12:30+0800   #notice +0800
GMT+8:  "2007-04-05T12:30+08     #notice +08```

### Date
2019-02-04 #notice no timezone available
```

### Constructor

Use constructor to create datetime / date object. You can make it timezone aware with ```tzinfo``` parameter, which is an **ZoneInfo** object.

```{python, results='hold'}
## Date Only
date      (2000,1,1)
type(date (2000,1,1))

## Datetime - TImezone Naive
datetime  (2000,1,1,23,15,55)
datetime  (year=2000,month=1,day=1,hour=23,minute=15,second=55)
type(datetime(2000,1,1,0,0,0))
```
#### Timezone Integration {-}

Datetime supports **timezone** through built-in library (refer [ZoneInfo](#zoneinfo) chapter). Initialize datetime with **```tzinfo``` ** parameter to have a timezone aware datetime.

```{python, results='hold'}
MY = ZoneInfo('Asia/Kuala_Lumpur')
NY = ZoneInfo('America/New_York')
UTC= ZoneInfo('UTC')

## Timezone Aware
datetime  (2000,1,1,23,15,55, tzinfo=NY)
```


### Class Methods

#### Now and Today  {-}

- Both **```now()```** and **```today()```** return current **system local**  datetime, which is **timezone naive**.
- **```utcnow()```** returns UTC datetime, which is also **timezone naive**.
- Only **```now()```** supports **```tz```** parameter to convert the time to desired timezone.
- **```today() / utcnow()** does not supports **```tz```** parameter.

```{python, results='hold', error=TRUE}
datetime.now()         ## local datetime
datetime.today()       ## local datetime, same as above
datetime.utcnow()      ## UTC datetime
datetime.now(tz=NY)    ## convert to New York timezone
datetime.today(tz=NY)  ## Error
datetime.utcnow(tz=NY) ## Error
```
#### Combine Data and Time (combine) {-}

Apply ```datetime.combine()``` class method on both **date and time**  objects to get **datetime**

```{python}
now = datetime.now()
datetime.combine(now.date(), now.time())
```

#### Convert from String (strptime)  {-}

Use **```strptime```** to convert string into **datetime** object. Refer [this cheatsheet](https://strftime.org/) for complete directives.
```
%I : 12-hour
%H : 24-hour
%M : Minute
%p : AM/PM
%y : 18
%Y : 2018
%b : Mar
%m : month (1 to 12)
%d : day
```

```{python, results='hold'}
datetime.strptime('2011-02-25', '%Y-%m-%d')
datetime.strptime('9-01-18',    '%d-%m-%y')
datetime.strptime('09-Mar-2018','%d-%b-%Y')
datetime.strptime('2/5/2018 4:49 PM', '%m/%d/%Y %I:%M %p')
```

#### Convert from ISO (fromisoformat) {-}

- **```fromisoformat()```** is the reverse of **```isoformat()```**.    
-  It actually **not ISO compliance**: when Z or +8 is included at the end of the string, Error is triggered.

```{python, results='hold', error=TRUE}
datetime.now().isoformat()                         ## checkout the iso format
datetime.fromisoformat("2019-02-05T10:22:33")      ## Good
datetime.fromisoformat("2019-02-05T10:22:33Z")     ## Error due to trailing 'Z'
datetime.fromisoformat("2019-02-05T10:22:33+0800") ## Errordue to trailing '+0800'
```
### Instance Attributes


```{python, results='hold'}
now = datetime.now(tz=MY)  ## initialize the instance
now.month
now.day
now.hour
now.minute
now.tzinfo                   ## this would be null if TZ parameter not specified
```

### Instance Methods

#### Update Data(.replace) {-}

Use **```replace()```** to change any parameters of the date/datetime during initialization.

```{python, results='hold'}
birthday = datetime(1997,3,1,10,35,21)   ## replace for datetime
birthday
birthday.replace(tzinfo=NY, year=1998, month=5)

holiday = date(1999,8,31)                ## replace for date
holiday
holiday.replace(year=2000)
```

#### Timezone Conversion (astimezone) {-}

- Use **```astimezone(<zoneinfo_timezone>)```** to convert a datetime to the desired timezone
- When applying this to  a **timezone naive** datetime, the datetime is assumed to be local timezone for conversion. Observe the example below.

```{python, results='hold'}
birthday = datetime(1997,3,1,10,35,21)  ## timezone naive, assumed to be local timezone for conversion
birthday.astimezone(NY)                 ## convert to NY time

birthday = datetime(1997,3,1,10,35,21, tzinfo=UTC)  ## timezone aware
birthday.astimezone(NY)                  ## convert to NY time
```

#### Convert to Time (.time)  {-}

```{python, jupyter_meta = list(scrolled = TRUE)}
datetime.now().time()
```
#### Convert to Date (.date)  {-}

```{python}
datetime.now().date()
```
#### Convert to String (strftime, isoformat)  {-}

Refer [this cheatsheet](https://strftime.org/) for complete directives.

```{python, results='hold'}
str( datetime.now() )
datetime.now().strftime('%d-%b-%Y')
datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%fZ')  ## ISO 8601 UTC
datetime.utcnow().isoformat()
```

#### Weekday  {-}

```{python, results='hold'}
now = datetime.now()
now.weekday()
```


### Instance Attributes

```{python, results='hold'}
datetime.now().year
datetime.now().month
datetime.now().day
datetime.now().hour
datetime.now().minute
```

### Operators

#### Difference (-) {-}

Use **```-```** to get the difference between two dates as **```timedelta```** object.

```{python, results='hold'}
dt1 = datetime(2000,1,1,10,25,35)
dt2 = datetime(2000,1,2,14,30,55)

dt2 - dt1
dt1 - dt2
```

#### Addition (+) {-}

Adding **```timedelta```** to a datetime to get an adjusted datetime. Note that there can be negative adjustment to any parameters of **timedelta**.

```{python, results='hold'}
delta = timedelta(days=5, hours=-5, minutes=30, seconds=10)
dt1   = datetime(2000,1,1,10,25,35)
delta  ## check the delta object
dt1    ## original datetime
dt1 + timedelta(days=5, hours=-5, minutes=30, seconds=10)  ## adjusted datetime
```

## Time

### Constructor

```{python, results='hold'}
print( time(2) )    ## specify hour only, minutes and seconds default to 0
print( time(2,15) ) ## seconds default to 0
print( time(hour=2,minute=15,second=30) )
```

### Instance Methods

```{python, results='hold'}
t1 = time(2,15,30)
t2 = t1.replace(hour=5, minute=30, second=55)
t1.isoformat()
t2.isoformat()
```

### Instance Attributes

```{python, results='hold'}
t = time(2,15,30)
t.hour
t.minute
t.second
```

## Timedelta

### Constructor

- Constructor does not support **years** argument.  

```{python, results='hold'}
delt = timedelta(days=365,minutes=33,seconds=15)
```

### Using With Datetime

- **```timedelta```** can be applied on  on **datetime** object.
- Timedelta **Cannot** be applied on **time object**  , because it potentially go beyond single day (24H).

```{python, results='hold'}
dt1  = datetime.now()
delt = timedelta(days=365,minutes=33,seconds=15)

delt
dt1
now + delt
```
